# Commands go through bash
# shell = "bash -c '{}'"

# Sway supports the default '#' comments, so it can be ommited
# 'rewrite' is also ommited, as it defaults to false
[[items]]
file = "~/.config/alacritty/base16.toml"
template = "alacritty"
rewrite = true


[[items]]
file = "~/.themes/flat-color/colors2"
template = "gtk"
subtemplate = "gtk2"
rewrite = true


[[items]]
file = "~/.themes/flat-color/colors3"
template = "gtk"
subtemplate = "gtk3"
rewrite = true
# [[items]]
# file = "~/.config/beautifuldiscord/style.css"
# template = "styles"
# subtemplate = "css-variables"
# # What if the configuration doesn't support '#' comments? Just change them!
# start= "/* Start flavours */"
# end = "/* End flavours */"