#!/bin/bash

source ~/.profile

########################################
# Run eww
#
# Arguments:
#   None
########################################
i3::eww() {
    
    eww kill
    eww daemon &> /dev/null
    eww open bar-window &> /dev/null
}

########################################
# Run picom
#
# Arguments:
#   None
########################################
i3::picom() {
    pkill picom
    sleep 0.5
    picom --daemon --config ~/.config/picom/picom.conf 
}

########################################
# Run feh
#
# Arguments:
#   None
######################################## 
i3::feh() {

    feh --bg-fill $(shuf -e -n1 ~/.config/wallpapers/*)
}


########################################
# Run startup programs
#
# Arguments:
#   None
########################################
i3::start() {

    i3::eww &
    i3::picom &
    i3::feh &

}

"$@"
