#!/bin/bash

########################################
# Function to print workspaces tags to be used in eww
#
# Arguments:
#   None
########################################
print-workspaces() {
    i3-msg -t get_workspaces | sed -E 's/\},\s*\{/\},\n\{/g' | ( 
        while read workspace ; do
        
            name=$(echo $workspace | cut -d ':' -f 4 | cut -d ',' -f 1 | tr -d '"')
            
            if [[ "$workspace" = *"focused\":true"* ]]; then
                class="workspace focused"   
            elif [[ "$workspace" = *"urgent\":true"* ]]; then
                class="workspace urgent"
            else 
                class="workspace"
            fi

            if [[ "$workspace" = *"["* ]]; then
                class="$class round-left square-right"
            elif [[ "$workspace" = *"["* ]]; then
                class="$class round-left square-right"
            elif [[ "$workspace" = *"]"* ]]; then
                class="$class square-left round-right"
            else 
                class="$class square"
            fi
            output="$output (eventbox :cursor \"hand\" :onclick \"i3-msg workspace $name\" (label :class \"$class\" :text \"$name\"))"
        done

        echo "(box :space-evenly false :class \"workspaces\" $output)"
    )
}

########################################
# Print workspaces tags when something has changed
#
# Arguments:
#   None
########################################
watch-workspaces() {

    # 
    while true; do
        pkill xprop
        xprop -root -spy _NET_CURRENT_DESKTOP | while read -r _ ; do
            print-workspaces
        done &
        sleep 10
    done
}

"$@"